### ISSUE TITLE
Search by map area errors with latest solr config

### ISSUE THREAD

**Issue by stevenvandervalk** [vecnet/dl-discovery#34]
The following error happens when submitting a query containing bbox format earthworks/geoblacklight previously used.

```
RSolr::Error::Http - 400 Bad Request Error: { 'responseHeader'=>{ 'status'=>400, 'QTime'=>1, 'params'=>{ 'mm'=>'6<-1 6<90%', 'qs'=>'1', 'q.alt'=>'*:*', 'facet.field'=>['dc_type_s', 'dc_creator_sm', 'vn_keyword_sm', URI: http://127.0.0.1:8983/solr/select?wt=ruby&qt=search&facet.field=dc_type_s&facet.field=dc_creator_sm&facet.field=vn_keyword_sm&facet.field=dct_spatial_sm&facet.field=dc_publisher_s&facet.field=dc_format_s&fq=%3A%22Intersects%28112.8515625+-76.39331166244494+166.9921875+68.59248658252947%29%22&start=0&rows=10&q.alt=*%3A*&facet=true&f.dc_type_s.facet.limit=11&f.dc_creator_sm.facet.limit=7&f.vn_keyword_sm.facet.limit=11&f.dct_spatial_sm.facet.limit=11&f.dc_publisher_s.facet.limit=7&f.dc_format_s.facet.limit=4&sort=score+desc%2C+dc_title_sort+asc&bq=%3A%22IsWithin%28112.8515625+-76.39331166244494+166.9921875+68.59248658252947%29%22%5E10 Backtrace: /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/blacklight-5.12.1/lib/blacklight/solr_repository.rb:44:in `block in send_and_receive' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/benchmarkable.rb:41:in `block in benchmark' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/2.1.0/benchmark.rb:294:in `realtime' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/benchmark.rb:12:in `ms' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/benchmarkable.rb:41:in `benchmark' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/blacklight-5.12.1/lib/blacklight/solr_repository.rb:42:in `send_and_receive' /Users/jc234325/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/blacklight-5.12.1/lib/blacklight/solr_repository.rb:28:in `search'

Rails.root: /Users/jc234325/Dropbox/eResearch/github/vecnet/dl-discovery

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"q"=>"",
 "showmap"=>"",
 "bbox"=>"112.8515625 -76.39331166244494 166.9921875 68.59248658252947",
 "_"=>"1429425474443"}
```

**Comment by stevenvandervalk** [comment]
Strangely unbroken by geoblacklight 0.9.2?

**Comment by dbrower** [comment]
Is the request URL correct? Should it be `
http://127.0.0.1:8983/solr/development/select?...`

On Sun, Apr 19, 2015 at 3:55 AM, Steve Vandervalk notifications@github.com
wrote:

> Strangely unbroken by geoblacklight 0.9.2?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vecnet/dl-discovery/issues/34#issuecomment-94248932.

## 

_Donald Brower, Ph.D._\* Digital Infrastructure Lead*
- Hesburgh Libraries — Digital Library Initiatives and Scholarship*

_University of Notre Dame_
208 Hesburgh Library
Notre Dame, IN 46556
_o:_ 574-631-1566
_e:_ dbrower@nd.edu

**Comment by stevenvandervalk** [comment]
No it isn't, you're correct. But I couldn't determine why that was occurring?
